### ISSUE TITLE
kafka-monitor service stuck in pending state

### ISSUE THREAD

**Issue by Analect** [samsung-cnct/k2-charts#60]
I amended the zookeeper chart to run up a single replica and same with kafka chart ... just to get this up and running.  It broadly works, except for the kafka-monitor ... where it's service gets stuck in a pending state, although the underlying pod is running, with logs below.  Is there some other dependency I'm missing?  Thanks.

```
2017-02-01T16:09:52.341860418Z + sleep 10
2017-02-01T16:10:02.342971476Z + bin/kafka-monitor-start.sh config/kafka-monitor.properties
2017-02-01T16:10:03.062742086Z log4j:ERROR Could not read configuration file from URL [file:/opt/kafka-monitor/bin/../config/log4j.properties].
2017-02-01T16:10:03.063973718Z java.io.FileNotFoundException: /opt/kafka-monitor/bin/../config/log4j.properties (No such file or directory)
2017-02-01T16:10:03.064237554Z 	at java.io.FileInputStream.open0(Native Method)
2017-02-01T16:10:03.064376725Z 	at java.io.FileInputStream.open(FileInputStream.java:195)
2017-02-01T16:10:03.064497884Z 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
2017-02-01T16:10:03.064619701Z 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
2017-02-01T16:10:03.064701196Z 	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
2017-02-01T16:10:03.064796651Z 	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
2017-02-01T16:10:03.064875147Z 	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:557)
2017-02-01T16:10:03.064961680Z 	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
2017-02-01T16:10:03.065255401Z 	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
2017-02-01T16:10:03.065359036Z 	at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:66)
2017-02-01T16:10:03.065436786Z 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:277)
2017-02-01T16:10:03.065555506Z 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
2017-02-01T16:10:03.065644819Z 	at com.linkedin.kmf.core.KafkaMonitor.<clinit>(KafkaMonitor.java:27)
2017-02-01T16:10:03.065765420Z log4j:ERROR Ignoring configuration file [file:/opt/kafka-monitor/bin/../config/log4j.properties].
2017-02-01T16:10:03.634247166Z log4j:WARN No appenders could be found for logger (com.linkedin.kmf.services.configs.ProduceServiceConfig).
2017-02-01T16:10:03.636081802Z log4j:WARN Please initialize the log4j system properly.
2017-02-01T16:10:03.636176176Z log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2017-02-01T16:10:05.697342363Z I> No access restrictor found, access to any MBean is allowed
```

**Comment by coffeepac** [comment]
@Analect can you please try and kill the running pod?  we suspect it will heal itself.  unsure why the config file is missing though, its part of the original image.

**Comment by Analect** [comment]
@coffeepac 
Thanks for the quick response.

I deleted the monitor pod a few times for it to respawn, but the logs are as above each time.
I ran `kubectl exec -it kafka-monitor-3478443908-11tff /bin/bash` to inspect things a bit more.

It seems from the logs `Could not read configuration file from URL [file:/opt/kafka-monitor/bin/../config/log4j.properties].` .. it's expecting to find a deeper hierarchy of files under /opt/kafka-monitor, which, as per below, doesn't necessarily exist.  Could it be that the image generated didn't copy over certain folders?

```
bash-4.3# pwd
/opt/kafka-monitor
bash-4.3# cd config/
bash-4.3# ls -ltr
total 0
lrwxrwxrwx    1 root     root            31 Feb  2 09:29 kafka-monitor.properties -> ..data/kafka-monitor.properties
bash-4.3# cat kafka-monitor.properties 
{ "end-to-end": { "class.name": "com.linkedin.kmf.tests.BasicEndToEndTest", "topic": "kmf-topic", "zookeeper.connect": "zk:2181/kafka", "bootstrap.servers": "kafka:9092", "produce.record.delay.ms": 100, "produce.producer.props": { "client.id": "kmf-client-id" },
"consume.latency.sla.ms": "20000" },
"reporter-service": { "class.name": "com.linkedin.kmf.services.DefaultMetricsReporterService", "report.interval.sec": 1, "report.metrics.list": [ "kmf.services:type=produce-service,name=*:produce-availability-avg", "kmf.services:type=consume-service,name=*:consume-availability-avg", "kmf.services:type=produce-service,name=*:records-produced-total", "kmf.services:type=consume-service,name=*:records-consumed-total", "kmf.services:type=consume-service,name=*:records-lost-total", "kmf.services:type=consume-service,name=*:records-duplicated-total", "kmf.services:type=consume-service,name=*:records-delay-ms-avg", "kmf.services:type=produce-service,name=*:produce-error-rate", "kmf.services:type=consume-service,name=*:consume-error-rate" ] },
"jetty-service": { "class.name": "com.linkedin.kmf.services.JettyService", "jetty.port": 8000 },
"jolokia-service": { "class.name": "com.linkedin.kmf.services.JolokiaService" } }bash-4.3# 
bash-4.3# cd ..
bash-4.3# cd bin/
bash-4.3# ls
kafka-monitor-start.sh  kmf-run-class.sh
```

It's not fully clear to me, but I'm assuming the image `quay.io/samsung_cnct/kafka-monitor:0.1` is derived from [this](https://github.com/samsung-cnct/kafka-monitor-kubernetes) repo.  It instucts:

> Ensure the kafka svc name in the .properties file matches your kafka cluster to monitor.

Is there any adjustment I need to make to get this running in the my cluster?

**Comment by Analect** [comment]
Or perhaps this is the source of my problem:

![image](https://cloud.githubusercontent.com/assets/4063815/22548826/49fdfb3c-e940-11e6-833c-ef66e086ee7e.png)

**Comment by coffeepac** [comment]
for the configuration file path, what you're showing from the running kafka-monitor pod seems to be correct.  the path to the config file is strange no doubt.  the '..' path segment is actually 'up a level in the directory tree'.  So /opt/kafka-monitor/bin/../config/log4j.properties  resolves to /opt/kafka-monitor/config/log4j.properties.  if that file is missing though, that would cause the app to fall over.  I'll take a look at the that now.

running out of static ips in GKE will probably prevent the kafka-monitor service from deploying successfully but that wouldn't effect the pod.

**Comment by coffeepac** [comment]
@Analect that file is missing from the kafka-monitor image we are using.  however, that isn't preventing kafka-monitor from starting for me.  I'll file a bug on this to fix the missing log config.

and I've just re-read your original post and you also said the kafka-monitor pod is fine but the service is pending.  running out of static ips in GKE will cause GKE to not be able to create a LoadBalancer type service.  Which kakfa-monitor wants.

If you don't want to use kafka-monitor you can remove it.  It is a good idea to have a monitoring point for your kafka cluster but its not required, especially for exploration.

**Comment by coffeepac** [comment]
haven't heard back from @Analect.  will happily re-open if he returns with more info.
